spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/interactio_db
    username: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    defer-datasource-initialization: false
    open-in-view: false
    show-sql: true

  main:
    banner-mode: off

server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8080